import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/mockito.dart';
import 'package:mockito/annotations.dart';
import 'package:dio/dio.dart';
import 'package:floq/features/auth/data/repositories/auth_repository_impl.dart';
import 'package:floq/core/services/api_client.dart';
import 'package:floq/core/services/secure_storage_service.dart';

@GenerateMocks([ApiClient, SecureStorageService, Dio])
void main() {
  // This file will be generated by build_runner, but we can write the test assuming it exists
  // For the sake of this environment, I'll use manual mocks if build_runner is not available or too slow.
  
  group('AuthRepositoryImpl', () {
    test('logout should clear storage', () async {
      // Manual mock for simplicity in this environment
      final mockStorage = MockSecureStorageService();
      final mockApiClient = MockApiClient();
      
      final repository = AuthRepositoryImpl(
        apiClient: mockApiClient,
        storage: mockStorage,
      );

      await repository.logout();

      verify(mockStorage.deleteTokens()).called(1);
      verify(mockStorage.deleteUser()).called(1);
    });
  });
}

// Manual mocks to ensure it runs without build_runner immediately
class MockSecureStorageService extends Mock implements SecureStorageService {
  @override
  Future<void> deleteTokens() => super.noSuchMethod(
        Invocation.method(#deleteTokens, []),
        returnValue: Future<void>.value(),
        returnValueForMissingStub: Future<void>.value(),
      );
  @override
  Future<void> deleteUser() => super.noSuchMethod(
        Invocation.method(#deleteUser, []),
        returnValue: Future<void>.value(),
        returnValueForMissingStub: Future<void>.value(),
      );
}

class MockApiClient extends Mock implements ApiClient {}
